name: Retrieve Secrets from Vault

on:
  workflow_dispatch:

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Secrets
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: "<YOUR_VAULT_URL>"
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            <engine>/data/<secret_path> <ENV_VAR_NAME>

      - name: Verify Retrieved Secret
        env:
          JWT_KEY: ${{ steps.vault.outputs.<ENV_VAR_NAME> }}
        run: |
          if [ "$<ENV_VAR_NAME>" != "<EXPECTED_VALUE>" ]; then
            echo "::error::❌ Secret mismatch! Expected <EXPECTED_VALUE> but got $<ENV_VAR_NAME>"
            exit 1
          else
            echo "✅ Secret matches expected value!"
          fi
