name: Retrieve Secrets from Vault

on:
  workflow_dispatch:

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Secrets
        id: vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://35.159.32.190:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            termodom/data/office/public/api JWT_KEY

      - name: Temporary Secret Verification
        env:
          JWT_KEY: ${{ steps.vault.outputs.JWT_KEY }}
        run: |
          if [ "$JWT_KEY" != "AS" ]; then
            echo "::error::Secret mismatch!"
            exit 1
          fi
